### ISSUE TITLE
Improving team workflow

### ISSUE THREAD

**Issue by briankarUB** [briankarUB/CGames#20]
I have in mind a few changes that can be made to the repo which will improve our workflow. I'll list them below:

- [x] Shared run configurations for local testing and builds
- [x] Migration to environment variable usage to prevent leaking secret info
- [x] Shared IDE code style settings
- [x] Make code style checks optional on CI builds
- [x] Remove coverage testing as it's confusing and not working properly
- [x] Improved `requirements.txt` version pinning so that version inconsistency doesn't cause problems (this doesn't seem to be a problem right now, but let's keep it that way)
- [x] Add more detailed instructions for setting up the project (including setting up a virtualenv, etc)

More will be added to this list if necessary.

**Comment by lonesai** [comment]
I'm open to all of these changes. Looks good!
