### ISSUE TITLE
Design a Logo for CGames

### ISSUE THREAD

**Issue by mhbiele** [briankarUB/CGames#39]
We are looking for someone to design and submit a logo for CGames that will appear on the homepage, on the page banner, and used as the avatar for social media accounts.

**Comment by hartloff** [comment]
Please change this to be a software engineering task. It's fine if you want to advertise this on Piazza as an open invitation, but you can't assume that your assigned developer will be a graphical artist. You can only assume that they can produce code.

**Comment by kai123456** [comment]
hey, buddy, did you finished this case already>??
