### ISSUE TITLE
Python topic lesson/game

### ISSUE THREAD

**Issue by alphathunderwave** [briankarUB/CGames#41]
Pick a python related topic and plan an assignment and/or a game to teach and reinforce the ideas.

**Comment by hartloff** [comment]
This is not clearly defined.

**Comment by notAmritpal** [comment]
Can you elaborate the issue?

**Comment by alphathunderwave** [comment]
Using Assignment 1 as a tutorial, make a new page (ex: assignment 2) that is a tutorial of a topic in python. 
https://docs.python.org/3/tutorial/index.html#tutorial-index is a good resource on intro topics.
This envoles making a new html file in the /templates/assignments directory that uses the default html template.
