### ISSUE TITLE
I can go to the next lesson without getting a minimum score

### ISSUE THREAD

**Issue by RedwanIbneSerajKhan** [briankarUB/CGames#75]
# Description

In your MVP, you guys said "The user is rewarded for correct answers and can proceed to the next part of the game upon meeting a minimum point requirement." But currently I can proceed to the next lesson without meeting a minimum point requirement.

#Video Representation of the bug

Here is a gif representing what I am talking about. 

![cgame minor bug](https://user-images.githubusercontent.com/28854577/38780920-8d760f44-40ab-11e8-97d8-3d54dd9f98c8.gif)

**Comment by cb56** [comment]
first of all, thanks for the feedback and especially for the gif. as a team, we decided to change this MVP feature. other users have asked for the ability to pick and choose which lessons to complete (in any order), so we've decided to do that
