### ISSUE TITLE
Assignment 2 Question 2 is wrong

### ISSUE THREAD

**Issue by jaimeenahn** [briankarUB/CGames#94]
`list = [“Yankees”,”Red Sox”,”Orioles”, “Blue Jays”]

list.sort()
list.reverse()
print(list)
print(list[2])`

This is the code of assignment 2 question 2. This question asks what is printed out after following statement. In this case, list and one of list elements will be printed. But there is only 4 slot, not 5, and the answer this question accept is the case till it executed only print(list). So, I think print(list[2]) is on there by mistake. This is very minor thing but I think you should know about this as a alpha tester.

![capture](https://user-images.githubusercontent.com/32367255/39050883-0425d3b4-4475-11e8-8614-e05bef92e1f8.JPG)

**Comment by briankarUB** [comment]
I think this is fixed in the next version already, thanks.
