### ISSUE TITLE
Wording for question 2 misleading/incorrect

### ISSUE THREAD

**Issue by arogers7** [briankarUB/CGames#95]
As I mentioned in my alpha tester feedback form, the following question https://imgur.com/a/PAJrGpi is not worded well. Value of a boolean should be True or False, if you want bool to be the correct answer, you should ask for the type instead of the value.

**Comment by briankarUB** [comment]
This is fixed in the next version

**Comment by arogers7** [comment]
I just opened it directly from your github this morning, if it was fixed, it is not in the current release

**Comment by briankarUB** [comment]
>Next
