### ISSUE TITLE
Go to different lesson directly

### ISSUE THREAD

**Issue by xingtongli** [briankarUB/CGames#97]
For the user want to go to the lesson 2 or others, they can go to the lesson directly. Creating buttons for different lessons will be better for these users.

**Comment by briankarUB** [comment]
If I understand, you mean to allow users to proceed to any lesson without having to click through each one?

**Comment by xingtongli** [comment]
Yes, for example, you can set lesson 1, lesson 2 buttons for user to see the lessons directly without finishing the lesson 1 firstly.

**Comment by cb56** [comment]
Appreciate the feedback. We've thought about this feature but haven't gotten around to implementing it. I'm going to work on it over the course of the next week
